# Generated by Django 3.2.18 on 2023-03-02 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='UserRating',
        ),
    ]
