# Generated by Django 3.2.18 on 2023-03-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_alter_userrating_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='published',
        ),
    ]
